  spring:
    application:
     name: eureka-client
    cloud:
     config:
      server:
       git:
        uri: https://github.com/badmanhy/ronSpringCloud/
        searchPaths: config-repo
        username: Username
        password: Password
  server:
    port: 8771
  # 心跳时间，即服务续约间隔时间（缺省为30s）
  eureka:
    instance:
     lease-renewal-interval-in-seconds: 5
     # 发呆时间，即服务续约到期时间（缺省为90s）
     lease-expiration-duration-in-seconds: 15
     # 开启健康检查（依赖spring-boot-starter-actuator）
    client:
     healthcheck:
      enabled: true
     serviceUrl:
      defaultZone: http://localhost:8888/eureka/


