server:
  port: 8778
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/badmanhy/ronSpringCloud/
          username: Username
          password: Password
          basedir: /Users/admin/code/myProjects/java/imooc/SpringCloud_Sell/config/basedir
         # searchPaths:config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      expose: "*"

