server:
  port: 8772
spring:
  application:
    name: sso-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/badmanhy/ronSpringCloud/
          searchPaths: config-repo
          username: Username
          password: Password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

swagger2:
  enable: true
